/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
/*
 * Vendored from the v0.2 branch — frozen along with the v0 SDK source.
 *
 * To regenerate (if the v0 contract surface ever changes — note: it
 * shouldn't, those contracts are deployed and final):
 *   git worktree add /tmp/quip-v0.2 v0.2
 *   cd /tmp/quip-v0.2
 *   # Replace hardhat.config.cts with a minimal config that imports
 *   # only "@nomicfoundation/hardhat-toolbox" and sets solidity v0.8.28
 *   # (paris, optimizer off, no metadata hash).
 *   # Strip @midl/* deps from package.json (they're file: refs to a
 *   # sibling dir that may not exist in your checkout).
 *   npm install && npx hardhat compile
 *   # Copy typechain-types/ into src/v0/typechain-types/ in this repo,
 *   # then delete: hardhat.d.ts, contracts/test/, factories/contracts/test/.
 *   # Trim the DummyContract / test re-exports from the three barrels.
 */
import type * as quipNetwork from "./@quip.network";
export type { quipNetwork };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { WOTSPlus } from "./@quip.network/hashsigs-solidity/contracts/WOTSPlus";
export { WOTSPlus__factory } from "./factories/@quip.network/hashsigs-solidity/contracts/WOTSPlus__factory";
export type { Deployer } from "./contracts/Deployer";
export { Deployer__factory } from "./factories/contracts/Deployer__factory";
export type { QuipFactory } from "./contracts/QuipFactory";
export { QuipFactory__factory } from "./factories/contracts/QuipFactory__factory";
export type { QuipWallet } from "./contracts/QuipWallet";
export { QuipWallet__factory } from "./factories/contracts/QuipWallet__factory";
