/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace WOTSPlus {
  export type WinternitzElementsStruct = { elements: BytesLike[] };

  export type WinternitzElementsStructOutput = [elements: string[]] & {
    elements: string[];
  };

  export type WinternitzAddressStruct = {
    publicSeed: BytesLike;
    publicKeyHash: BytesLike;
  };

  export type WinternitzAddressStructOutput = [
    publicSeed: string,
    publicKeyHash: string
  ] & { publicSeed: string; publicKeyHash: string };

  export type WinternitzMessageStruct = { messageHash: BytesLike };

  export type WinternitzMessageStructOutput = [messageHash: string] & {
    messageHash: string;
  };
}

export interface WOTSPlusInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ChainLen"
      | "HashLen"
      | "LgChainLen"
      | "MessageLen"
      | "NumChecksumChunks"
      | "NumMessageChunks"
      | "NumSignatureChunks"
      | "PublicKeySize"
      | "SignatureSize"
      | "chain"
      | "generateKeyPair"
      | "generateRandomizationElements"
      | "sign"
      | "verify"
      | "verifyWithRandomizationElements"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "ChainLen", values?: undefined): string;
  encodeFunctionData(functionFragment: "HashLen", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "LgChainLen",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MessageLen",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "NumChecksumChunks",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "NumMessageChunks",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "NumSignatureChunks",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PublicKeySize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SignatureSize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "chain",
    values: [
      BytesLike,
      WOTSPlus.WinternitzElementsStruct,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "generateKeyPair",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "generateRandomizationElements",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sign",
    values: [BytesLike, WOTSPlus.WinternitzMessageStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [
      WOTSPlus.WinternitzAddressStruct,
      WOTSPlus.WinternitzMessageStruct,
      WOTSPlus.WinternitzElementsStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyWithRandomizationElements",
    values: [
      WOTSPlus.WinternitzAddressStruct,
      WOTSPlus.WinternitzMessageStruct,
      WOTSPlus.WinternitzElementsStruct,
      WOTSPlus.WinternitzElementsStruct
    ]
  ): string;

  decodeFunctionResult(functionFragment: "ChainLen", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "HashLen", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "LgChainLen", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MessageLen", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "NumChecksumChunks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "NumMessageChunks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "NumSignatureChunks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PublicKeySize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SignatureSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "chain", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "generateKeyPair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "generateRandomizationElements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sign", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyWithRandomizationElements",
    data: BytesLike
  ): Result;
}

export interface WOTSPlus extends BaseContract {
  connect(runner?: ContractRunner | null): WOTSPlus;
  waitForDeployment(): Promise<this>;

  interface: WOTSPlusInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ChainLen: TypedContractMethod<[], [bigint], "view">;

  HashLen: TypedContractMethod<[], [bigint], "view">;

  LgChainLen: TypedContractMethod<[], [bigint], "view">;

  MessageLen: TypedContractMethod<[], [bigint], "view">;

  NumChecksumChunks: TypedContractMethod<[], [bigint], "view">;

  NumMessageChunks: TypedContractMethod<[], [bigint], "view">;

  NumSignatureChunks: TypedContractMethod<[], [bigint], "view">;

  PublicKeySize: TypedContractMethod<[], [bigint], "view">;

  SignatureSize: TypedContractMethod<[], [bigint], "view">;

  chain: TypedContractMethod<
    [
      prevChainOut: BytesLike,
      randomizationElements: WOTSPlus.WinternitzElementsStruct,
      index: BigNumberish,
      steps: BigNumberish
    ],
    [string],
    "view"
  >;

  generateKeyPair: TypedContractMethod<
    [privateSeed: BytesLike],
    [[WOTSPlus.WinternitzAddressStructOutput, string]],
    "view"
  >;

  generateRandomizationElements: TypedContractMethod<
    [publicSeed: BytesLike],
    [WOTSPlus.WinternitzElementsStructOutput],
    "view"
  >;

  sign: TypedContractMethod<
    [privateKey: BytesLike, message: WOTSPlus.WinternitzMessageStruct],
    [string[]],
    "view"
  >;

  verify: TypedContractMethod<
    [
      quipAddress: WOTSPlus.WinternitzAddressStruct,
      message: WOTSPlus.WinternitzMessageStruct,
      signature: WOTSPlus.WinternitzElementsStruct
    ],
    [boolean],
    "view"
  >;

  verifyWithRandomizationElements: TypedContractMethod<
    [
      quipAddress: WOTSPlus.WinternitzAddressStruct,
      message: WOTSPlus.WinternitzMessageStruct,
      signature: WOTSPlus.WinternitzElementsStruct,
      randomizationElements: WOTSPlus.WinternitzElementsStruct
    ],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ChainLen"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "HashLen"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LgChainLen"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MessageLen"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "NumChecksumChunks"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "NumMessageChunks"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "NumSignatureChunks"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PublicKeySize"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SignatureSize"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "chain"
  ): TypedContractMethod<
    [
      prevChainOut: BytesLike,
      randomizationElements: WOTSPlus.WinternitzElementsStruct,
      index: BigNumberish,
      steps: BigNumberish
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "generateKeyPair"
  ): TypedContractMethod<
    [privateSeed: BytesLike],
    [[WOTSPlus.WinternitzAddressStructOutput, string]],
    "view"
  >;
  getFunction(
    nameOrSignature: "generateRandomizationElements"
  ): TypedContractMethod<
    [publicSeed: BytesLike],
    [WOTSPlus.WinternitzElementsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "sign"
  ): TypedContractMethod<
    [privateKey: BytesLike, message: WOTSPlus.WinternitzMessageStruct],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<
    [
      quipAddress: WOTSPlus.WinternitzAddressStruct,
      message: WOTSPlus.WinternitzMessageStruct,
      signature: WOTSPlus.WinternitzElementsStruct
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyWithRandomizationElements"
  ): TypedContractMethod<
    [
      quipAddress: WOTSPlus.WinternitzAddressStruct,
      message: WOTSPlus.WinternitzMessageStruct,
      signature: WOTSPlus.WinternitzElementsStruct,
      randomizationElements: WOTSPlus.WinternitzElementsStruct
    ],
    [boolean],
    "view"
  >;

  filters: {};
}
