/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace WOTSPlus {
  export type WinternitzAddressStruct = {
    publicSeed: BytesLike;
    publicKeyHash: BytesLike;
  };

  export type WinternitzAddressStructOutput = [
    publicSeed: string,
    publicKeyHash: string
  ] & { publicSeed: string; publicKeyHash: string };

  export type WinternitzElementsStruct = { elements: BytesLike[] };

  export type WinternitzElementsStructOutput = [elements: string[]] & {
    elements: string[];
  };
}

export interface QuipWalletInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "changePqOwner"
      | "executeWithWinternitz"
      | "getExecuteFee"
      | "getTransferFee"
      | "initialize"
      | "owner"
      | "pqOwner"
      | "quipFactory"
      | "transferWithWinternitz"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "pqTransfer"): EventFragment;

  encodeFunctionData(
    functionFragment: "changePqOwner",
    values: [
      WOTSPlus.WinternitzAddressStruct,
      WOTSPlus.WinternitzElementsStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeWithWinternitz",
    values: [
      WOTSPlus.WinternitzAddressStruct,
      WOTSPlus.WinternitzElementsStruct,
      AddressLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getExecuteFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTransferFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [WOTSPlus.WinternitzAddressStruct]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pqOwner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "quipFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferWithWinternitz",
    values: [
      WOTSPlus.WinternitzAddressStruct,
      WOTSPlus.WinternitzElementsStruct,
      AddressLike,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "changePqOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeWithWinternitz",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExecuteFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransferFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pqOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "quipFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferWithWinternitz",
    data: BytesLike
  ): Result;
}

export namespace pqTransferEvent {
  export type InputTuple = [
    amount: BigNumberish,
    when: BigNumberish,
    pqFrom: WOTSPlus.WinternitzAddressStruct,
    pqNext: WOTSPlus.WinternitzAddressStruct,
    to: AddressLike
  ];
  export type OutputTuple = [
    amount: bigint,
    when: bigint,
    pqFrom: WOTSPlus.WinternitzAddressStructOutput,
    pqNext: WOTSPlus.WinternitzAddressStructOutput,
    to: string
  ];
  export interface OutputObject {
    amount: bigint;
    when: bigint;
    pqFrom: WOTSPlus.WinternitzAddressStructOutput;
    pqNext: WOTSPlus.WinternitzAddressStructOutput;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface QuipWallet extends BaseContract {
  connect(runner?: ContractRunner | null): QuipWallet;
  waitForDeployment(): Promise<this>;

  interface: QuipWalletInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  changePqOwner: TypedContractMethod<
    [
      newPqOwner: WOTSPlus.WinternitzAddressStruct,
      pqSig: WOTSPlus.WinternitzElementsStruct
    ],
    [void],
    "nonpayable"
  >;

  executeWithWinternitz: TypedContractMethod<
    [
      nextPqOwner: WOTSPlus.WinternitzAddressStruct,
      pqSig: WOTSPlus.WinternitzElementsStruct,
      target: AddressLike,
      opdata: BytesLike
    ],
    [[boolean, string]],
    "payable"
  >;

  getExecuteFee: TypedContractMethod<[], [bigint], "view">;

  getTransferFee: TypedContractMethod<[], [bigint], "view">;

  initialize: TypedContractMethod<
    [newPqOwner: WOTSPlus.WinternitzAddressStruct],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pqOwner: TypedContractMethod<
    [],
    [[string, string] & { publicSeed: string; publicKeyHash: string }],
    "view"
  >;

  quipFactory: TypedContractMethod<[], [string], "view">;

  transferWithWinternitz: TypedContractMethod<
    [
      nextPqOwner: WOTSPlus.WinternitzAddressStruct,
      pqSig: WOTSPlus.WinternitzElementsStruct,
      to: AddressLike,
      value: BigNumberish
    ],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "changePqOwner"
  ): TypedContractMethod<
    [
      newPqOwner: WOTSPlus.WinternitzAddressStruct,
      pqSig: WOTSPlus.WinternitzElementsStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeWithWinternitz"
  ): TypedContractMethod<
    [
      nextPqOwner: WOTSPlus.WinternitzAddressStruct,
      pqSig: WOTSPlus.WinternitzElementsStruct,
      target: AddressLike,
      opdata: BytesLike
    ],
    [[boolean, string]],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getExecuteFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTransferFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [newPqOwner: WOTSPlus.WinternitzAddressStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pqOwner"
  ): TypedContractMethod<
    [],
    [[string, string] & { publicSeed: string; publicKeyHash: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "quipFactory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferWithWinternitz"
  ): TypedContractMethod<
    [
      nextPqOwner: WOTSPlus.WinternitzAddressStruct,
      pqSig: WOTSPlus.WinternitzElementsStruct,
      to: AddressLike,
      value: BigNumberish
    ],
    [void],
    "payable"
  >;

  getEvent(
    key: "pqTransfer"
  ): TypedContractEvent<
    pqTransferEvent.InputTuple,
    pqTransferEvent.OutputTuple,
    pqTransferEvent.OutputObject
  >;

  filters: {
    "pqTransfer(uint256,uint256,tuple,tuple,address)": TypedContractEvent<
      pqTransferEvent.InputTuple,
      pqTransferEvent.OutputTuple,
      pqTransferEvent.OutputObject
    >;
    pqTransfer: TypedContractEvent<
      pqTransferEvent.InputTuple,
      pqTransferEvent.OutputTuple,
      pqTransferEvent.OutputObject
    >;
  };
}
