// Copyright (C) 2025 quip.network
//
// SPDX-License-Identifier: AGPL-3.0-or-later

/**
 * Release Script
 *
 * Creates a new release by:
 * 1. Compiling contracts with current settings
 * 2. Computing CREATE3 addresses for WOTSPlus, QuipFactory, and QuipWallet
 * 3. Saving bytecode to deployments/bytecode/
 * 4. Updating latest.json references
 * 5. Updating src/addresses.json
 *
 * CREATE3 addresses depend only on the Deployer address and per-contract salt,
 * not on bytecode. Salts follow the pattern: keccak256("QUIP:<Name>:V1").
 *
 * Note: Deployer contract is NOT updated as it's deployed via CREATE (nonce=1),
 * not CREATE3, and its address is fixed across all networks.
 *
 * Usage:
 *   bun run release
 *   npm run release
 */

import hre from "hardhat";
import fs from "fs";
import path from "path";

// eslint-disable-next-line @typescript-eslint/no-require-imports
const { DEPLOYMENT_SALT, contractSalt, computeCreate3Address } = require("../lib/deploy.cts");

const DEPLOYER_ADDRESS = "0xF768b4E4A314C9119587b8Cd35a89bDC228290b5";
const BYTECODE_DIR = path.join(__dirname, "../deployments/bytecode");
const ADDRESSES_FILE = path.join(__dirname, "../src/addresses.json");

interface BytecodeRelease {
  _comment: string;
  address: string;
  chainId: string;
  network: string;
  deploymentMethod: string;
  deployer: string;
  salt: string;
  compiler: {
    version: string;
    evmVersion: string;
    optimizer: { enabled: boolean; runs: number };
    metadata: { bytecodeHash: string };
  };
  linkedLibraries?: Record<string, string>;
  constructorArgsDescription?: string;
  creationBytecode: string;
  deployedBytecode: string;
}

async function main() {
  console.log("=".repeat(60));
  console.log("Quip Network Contract Release");
  console.log("=".repeat(60));

  // Get compiler info
  const solcVersion = "0.8.28+commit.7893614a";

  console.log(`\nCompiler: Solidity ${solcVersion}`);
  console.log(`EVM Version: paris`);
  console.log(`Optimizer: disabled (200 runs)`);
  console.log(`Metadata: bytecodeHash=none`);
  console.log(`Base salt: ${DEPLOYMENT_SALT}`);
  console.log(`Deployer: ${DEPLOYER_ADDRESS}`);

  // 1. Get WOTSPlus bytecode and compute CREATE3 address
  console.log("\n" + "-".repeat(60));
  console.log("WOTSPlus Library");
  console.log("-".repeat(60));

  const WOTSPlus = await hre.ethers.getContractFactory(
    "@quip.network/hashsigs-solidity-0.1.0/contracts/WOTSPlus.sol:WOTSPlus"
  );
  const wotsBytecode = WOTSPlus.bytecode;
  const wotsSalt = contractSalt(hre, "WOTSPlus");
  const wotsAddress = computeCreate3Address(hre, DEPLOYER_ADDRESS, wotsSalt);

  console.log(`Creation bytecode: ${wotsBytecode.length / 2 - 1} bytes`);
  console.log(`Salt: ${wotsSalt}`);
  console.log(`CREATE3 Address: ${wotsAddress}`);

  // Get deployed bytecode by deploying to hardhat network temporarily
  const wotsDeployedBytecode = await getDeployedBytecode(wotsBytecode);
  console.log(`Deployed bytecode: ${wotsDeployedBytecode.length / 2 - 1} bytes`);

  // Save WOTSPlus release
  const wotsRelease: BytecodeRelease = {
    _comment: "WOTSPlus library bytecode for CREATE3 deployment. Generated by release script.",
    address: wotsAddress,
    chainId: "*",
    network: "all EVM networks",
    deploymentMethod: "CREATE3 via Deployer",
    deployer: DEPLOYER_ADDRESS,
    salt: wotsSalt,
    compiler: {
      version: solcVersion,
      evmVersion: "paris",
      optimizer: { enabled: false, runs: 200 },
      metadata: { bytecodeHash: "none" },
    },
    creationBytecode: wotsBytecode,
    deployedBytecode: wotsDeployedBytecode,
  };

  await saveRelease("WOTSPlus.sol", wotsAddress, wotsRelease);

  // 2. Get QuipFactory bytecode and compute CREATE3 address
  console.log("\n" + "-".repeat(60));
  console.log("QuipFactory Contract");
  console.log("-".repeat(60));

  // QuipFactory needs WOTSPlus library linked
  const QuipFactory = await hre.ethers.getContractFactory("QuipFactory", {
    libraries: {
      "@quip.network/hashsigs-solidity-0.1.0/contracts/WOTSPlus.sol:WOTSPlus": wotsAddress,
    },
  });

  // Constructor: (address payable initialOwner, uint256 maxFee_)
  // Both vary per deployment, so we use placeholders for the release bytecode.
  const placeholderOwner = "0x0000000000000000000000000000000000000000";
  const placeholderMaxFee = hre.ethers.parseEther("0.1");
  const encodedParams = QuipFactory.interface.encodeDeploy([
    placeholderOwner,
    placeholderMaxFee,
  ]);
  const factoryBytecodeWithParams = QuipFactory.bytecode + encodedParams.slice(2);

  const factorySalt = contractSalt(hre, "QuipFactory");
  const factoryAddress = computeCreate3Address(hre, DEPLOYER_ADDRESS, factorySalt);

  console.log(`Base bytecode: ${QuipFactory.bytecode.length / 2 - 1} bytes`);
  console.log(`With constructor args: ${factoryBytecodeWithParams.length / 2 - 1} bytes`);
  console.log(`Salt: ${factorySalt}`);
  console.log(`CREATE3 Address: ${factoryAddress}`);

  // Get deployed bytecode
  const factoryDeployedBytecode = await getDeployedBytecode(factoryBytecodeWithParams);
  console.log(`Deployed bytecode: ${factoryDeployedBytecode.length / 2 - 1} bytes`);

  // Save QuipFactory release
  const factoryRelease: BytecodeRelease = {
    _comment: "QuipFactory bytecode for CREATE3 deployment. Generated by release script.",
    address: factoryAddress,
    chainId: "*",
    network: "all EVM networks",
    deploymentMethod: "CREATE3 via Deployer",
    deployer: DEPLOYER_ADDRESS,
    salt: factorySalt,
    compiler: {
      version: solcVersion,
      evmVersion: "paris",
      optimizer: { enabled: false, runs: 200 },
      metadata: { bytecodeHash: "none" },
    },
    linkedLibraries: {
      "WOTSPlus": wotsAddress,
    },
    constructorArgsDescription: "constructor(address payable initialOwner, uint256 maxFee_) - address shown uses placeholder owner 0x0 and maxFee 0.1 ether",
    creationBytecode: factoryBytecodeWithParams,
    deployedBytecode: factoryDeployedBytecode,
  };

  await saveRelease("QuipFactory.sol", factoryAddress, factoryRelease);

  // 3. Get QuipWallet bytecode and compute CREATE3 address
  console.log("\n" + "-".repeat(60));
  console.log("QuipWallet Implementation");
  console.log("-".repeat(60));

  // QuipWallet needs WOTSPlus library linked
  const QuipWallet = await hre.ethers.getContractFactory("QuipWallet", {
    libraries: {
      "@quip.network/hashsigs-solidity-0.1.0/contracts/WOTSPlus.sol:WOTSPlus": wotsAddress,
    },
  });

  // Constructor: (address payable factory_)
  const walletEncodedParams = QuipWallet.interface.encodeDeploy([factoryAddress]);
  const walletBytecodeWithParams = QuipWallet.bytecode + walletEncodedParams.slice(2);

  const walletSalt = contractSalt(hre, "QuipWallet");
  const walletAddress = computeCreate3Address(hre, DEPLOYER_ADDRESS, walletSalt);

  console.log(`Base bytecode: ${QuipWallet.bytecode.length / 2 - 1} bytes`);
  console.log(`With constructor args: ${walletBytecodeWithParams.length / 2 - 1} bytes`);
  console.log(`Salt: ${walletSalt}`);
  console.log(`CREATE3 Address: ${walletAddress}`);

  // Get deployed bytecode
  const walletDeployedBytecode = await getDeployedBytecode(walletBytecodeWithParams);
  console.log(`Deployed bytecode: ${walletDeployedBytecode.length / 2 - 1} bytes`);

  // Save QuipWallet release
  const walletRelease: BytecodeRelease = {
    _comment: "QuipWallet implementation bytecode for CREATE3 deployment. Generated by release script.",
    address: walletAddress,
    chainId: "*",
    network: "all EVM networks",
    deploymentMethod: "CREATE3 via Deployer",
    deployer: DEPLOYER_ADDRESS,
    salt: walletSalt,
    compiler: {
      version: solcVersion,
      evmVersion: "paris",
      optimizer: { enabled: false, runs: 200 },
      metadata: { bytecodeHash: "none" },
    },
    linkedLibraries: {
      "WOTSPlus": wotsAddress,
    },
    constructorArgsDescription: "constructor(address payable factory_) - factory is the QuipFactory CREATE3 address",
    creationBytecode: walletBytecodeWithParams,
    deployedBytecode: walletDeployedBytecode,
  };

  await saveRelease("QuipWallet.sol", walletAddress, walletRelease);

  // 4. Update addresses.json
  console.log("\n" + "-".repeat(60));
  console.log("Updating addresses.json");
  console.log("-".repeat(60));

  const addresses = {
    Deployer: DEPLOYER_ADDRESS,
    WOTSPlus: wotsAddress,
    QuipFactory: factoryAddress,
    QuipWallet: walletAddress,
  };

  fs.writeFileSync(ADDRESSES_FILE, JSON.stringify(addresses, null, 2) + "\n");
  console.log(`Updated: ${ADDRESSES_FILE}`);

  // Summary
  console.log("\n" + "=".repeat(60));
  console.log("Release Complete");
  console.log("=".repeat(60));
  console.log(`\nAddresses:`);
  console.log(`  Deployer:    ${DEPLOYER_ADDRESS} (unchanged)`);
  console.log(`  WOTSPlus:    ${wotsAddress}`);
  console.log(`  QuipFactory: ${factoryAddress}`);
  console.log(`  QuipWallet:  ${walletAddress}`);
  console.log(`\nBytecode saved to: ${BYTECODE_DIR}`);
  console.log(`\nNext steps:`);
  console.log(`  1. Review changes: git diff`);
  console.log(`  2. Run tests: npm test`);
  console.log(`  3. Commit: git commit -am "Release new bytecode"`);
}

async function getDeployedBytecode(creationBytecode: string): Promise<string> {
  // Deploy to hardhat network to get runtime bytecode
  const [signer] = await hre.ethers.getSigners();
  const tx = await signer.sendTransaction({ data: creationBytecode });
  const receipt = await tx.wait();
  if (!receipt?.contractAddress) {
    throw new Error("Failed to deploy contract");
  }
  return await hre.ethers.provider.getCode(receipt.contractAddress);
}

async function saveRelease(
  contractDir: string,
  address: string,
  release: BytecodeRelease
): Promise<void> {
  const dir = path.join(BYTECODE_DIR, contractDir);
  fs.mkdirSync(dir, { recursive: true });

  // Save release file
  const releaseFile = path.join(dir, `${address}.json`);
  fs.writeFileSync(releaseFile, JSON.stringify(release, null, 2) + "\n");
  console.log(`Saved: ${releaseFile}`);

  // Update latest.json
  const latestFile = path.join(dir, "latest.json");
  const latest = {
    _comment: `Reference to the current ${contractDir.replace(".sol", "")} release`,
    address: address,
    file: `${address}.json`,
  };
  fs.writeFileSync(latestFile, JSON.stringify(latest, null, 2) + "\n");
  console.log(`Updated: ${latestFile}`);
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
