// Copyright (C) 2025 quip.network
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
import {
  type Address,
  type Hex,
  type PublicClient,
  type WalletClient,
  type EIP1193Provider,
  createPublicClient,
  createWalletClient,
  custom,
  zeroAddress,
  parseEventLogs,
} from "viem";

import { quipFactoryAbi } from "./abi/QuipFactory.js";
import {
  getVaultAddress,
  getNetworkAddresses,
  CHAIN_IDS,
} from "./addresses.js";
import { QuipSigner } from "./signer.js";
import { QuipWalletClient } from "./walletClient.js";
import { withDecodedError } from "./internal/decodeError.js";
import { tryMulticall } from "./internal/multicall.js";
import {
  type TxOptions,
  type ContractCallParams,
  prepareTx,
} from "./gas.js";
import {
  WalletNotInitializedError,
  WalletAlreadyExistsError,
  NoVaultFoundError,
  InvalidSignerError,
  NotConnectedError,
  IncorrectTransactionKeyAmountError,
  IncorrectRecoveryKeyAmountError,
  PartialMulticallResultError,
} from "./errors.js";
import {
  type WinternitzAddress,
  encodeInit,
  TRANSACTION_KEY_INIT_AMOUNT,
  RECOVERY_KEY_AMOUNT,
} from "./wotsCodec.js";

/// Aggregated factory state — one multicall round-trip's worth of view
/// reads. Useful for an admin dashboard or pre-flight overview.
export interface FactoryState {
  owner: Address;
  pendingOwner: Address;
  creationFee: bigint;
  executeFee: bigint;
  maxFee: bigint;
  latestWalletImpl: Address;
  vettedCodeCount: bigint;
}

export class QuipClient {
  private publicClient: PublicClient;
  private walletClient: WalletClient;
  private account?: Address;
  private factoryAddress?: Address;
  private chainId?: number;
  private initializationPromise: Promise<void>;

  /**
   * Create a QuipClient instance
   * Works with any EIP-1193 compatible provider
   *
   * @param provider - An EIP-1193 compatible provider
   */
  constructor(provider: EIP1193Provider) {
    const transport = custom(provider);
    this.publicClient = createPublicClient({ transport });
    this.walletClient = createWalletClient({ transport });
    this.initializationPromise = this.initialize();
  }

  /**
   * Factory method for creating QuipClient instances
   * Provides a cleaner async initialization pattern
   */
  static async create(
    provider: EIP1193Provider
  ): Promise<QuipClient> {
    const client = new QuipClient(provider);
    await client.initializationPromise;
    return client;
  }

  private async initialize() {
    await this.detectNetwork();
    await this.setAccount();
    await this.setQuipFactory();
  }

  private async setAccount() {
    const [address] = await this.walletClient.getAddresses();
    this.account = address;
  }

  private async detectNetwork() {
    this.chainId = await this.publicClient.getChainId();
  }

  private async setQuipFactory() {
    const addresses = getNetworkAddresses(this.chainId);
    this.factoryAddress = addresses.QuipFactory;
  }

  /**
   * Get the current chain ID
   */
  getChainId(): number {
    if (!this.chainId) {
      throw new WalletNotInitializedError();
    }
    return this.chainId;
  }

  /**
   * Check if connected to MIDL network
   */
  isMidlNetwork(): boolean {
    return this.chainId === CHAIN_IDS.MIDL_TESTNET;
  }

  /**
   * Get the connected wallet's owner address
   */
  async getOwnerAddress(): Promise<Address> {
    await this.initializationPromise;
    if (!this.account) {
      throw new NotConnectedError();
    }
    return this.account;
  }

  async getCreationFee(): Promise<bigint> {
    await this.initializationPromise;
    return await withDecodedError(
      this.publicClient.readContract({
        address: this.factoryAddress!,
        abi: quipFactoryAbi,
        functionName: "creationFee",
      })
    );
  }

  /// Deploy a new QuipWallet via `deployLatestWalletProxy`. The contract
  /// init payload encodes ALL of the wallet's initial keys: one disaster
  /// recovery key, one ownership key, five transaction keys, ten recovery
  /// keys. By default each is freshly generated by `quipSigner` for this
  /// `vaultId`. Callers may supply their own to support pre-generated /
  /// offline-stored key material.
  ///
  /// All key material is recoverable later from on-chain state plus the
  /// signer's `quantumSecret`: every `publicSeed` is readable via
  /// `keyAt(...)` / `getDisasterRecoveryKey()` / `getOwnershipKey()`, and
  /// `quipSigner.recoverKeyPair(vaultId, publicSeed)` deterministically
  /// regenerates the private key. The user's only off-chain backup
  /// obligation is the `quantumSecret` itself — analogous to a BIP39
  /// seed phrase.
  async createWallet(
    vaultId: Hex,
    quipSigner: QuipSigner,
    keys: {
      disasterRecoveryKey?: WinternitzAddress;
      ownershipKey?: WinternitzAddress;
      transactionKeys?: WinternitzAddress[];
      recoveryKeys?: WinternitzAddress[];
    } = {},
    opts: TxOptions = {}
  ): Promise<QuipWalletClient> {
    await this.initializationPromise;

    const creationFee = await this.getCreationFee();

    const existingWalletAddress = await withDecodedError(
      this.publicClient.readContract({
        address: this.factoryAddress!,
        abi: quipFactoryAbi,
        functionName: "quips",
        args: [this.account!, vaultId],
      })
    );

    if (existingWalletAddress !== zeroAddress) {
      throw new WalletAlreadyExistsError(vaultId);
    }

    const disaster =
      keys.disasterRecoveryKey ??
      quipSigner.generateKeyPair(vaultId).publicKey;
    const ownership =
      keys.ownershipKey ?? quipSigner.generateKeyPair(vaultId).publicKey;
    const txnKeys =
      keys.transactionKeys ??
      Array.from({ length: TRANSACTION_KEY_INIT_AMOUNT }, () =>
        quipSigner.generateKeyPair(vaultId).publicKey
      );
    const recoveryKeys =
      keys.recoveryKeys ??
      Array.from({ length: RECOVERY_KEY_AMOUNT }, () =>
        quipSigner.generateKeyPair(vaultId).publicKey
      );

    if (txnKeys.length !== TRANSACTION_KEY_INIT_AMOUNT) {
      throw new IncorrectTransactionKeyAmountError();
    }
    if (recoveryKeys.length !== RECOVERY_KEY_AMOUNT) {
      throw new IncorrectRecoveryKeyAmountError();
    }

    const initPayload = encodeInit(disaster, ownership, txnKeys, recoveryKeys);

    // Route through the shared write pipeline so balance preflight,
    // simulation (catches `InsufficientCreationFee` / deprecated impl /
    // unvetted impl), gas estimation, and typed-error decoding all behave
    // the same way as wallet writes.
    const contractCall: ContractCallParams = {
      address: this.factoryAddress!,
      abi: quipFactoryAbi,
      functionName: "deployLatestWalletProxy",
      args: [vaultId, this.account!, initPayload],
      value: creationFee,
      account: this.account!,
    };
    const prepared = await prepareTx({
      publicClient: this.publicClient,
      contractParams: contractCall,
      totalValue: creationFee,
      opts,
    });

    const hash = await withDecodedError(
      this.walletClient.writeContract({
        chain: null,
        ...contractCall,
        gas: prepared.gas,
        ...prepared.fees,
        ...(prepared.nonce !== undefined && { nonce: prepared.nonce }),
      } as Parameters<WalletClient["writeContract"]>[0])
    );

    const receipt = await this.publicClient.waitForTransactionReceipt({
      hash,
    });

    const logs = parseEventLogs({
      abi: quipFactoryAbi,
      logs: receipt.logs,
      eventName: "QuipCreated",
    });
    const newWalletAddress = logs[0].args.quip;

    return new QuipWalletClient(
      quipSigner,
      vaultId,
      newWalletAddress,
      this.publicClient,
      this.walletClient,
      this.account!,
      this.chainId!
    );
  }

  async getVault(
    vaultId: Hex,
    quipSigner: QuipSigner
  ): Promise<QuipWalletClient> {
    await this.initializationPromise;

    const walletAddress = await withDecodedError(
      this.publicClient.readContract({
        address: this.factoryAddress!,
        abi: quipFactoryAbi,
        functionName: "quips",
        args: [this.account!, vaultId],
      })
    );

    if (walletAddress === zeroAddress) {
      throw new NoVaultFoundError(vaultId);
    }

    const client = new QuipWalletClient(
      quipSigner,
      vaultId,
      walletAddress,
      this.publicClient,
      this.walletClient,
      this.account!,
      this.chainId!
    );

    // Check if we have the right signer: regenerate the keypair from the
    // head transaction key's publicSeed and confirm the publicKeyHash
    // matches. This only proves the signer can produce key 0; if the
    // wallet has been operated concurrently by multiple signers the head
    // may belong to one and not the other. For most flows that's fine.
    const headKey = await client.getHeadTransactionKey();
    const keypair = quipSigner.recoverKeyPair(vaultId, headKey.publicSeed);
    if (keypair.publicKey.publicKeyHash !== headKey.publicKeyHash) {
      throw new InvalidSignerError();
    }
    return client;
  }

  async getVaultAddress(vaultId: Hex): Promise<Address> {
    await this.initializationPromise;
    return getVaultAddress(vaultId, this.chainId);
  }

  async getVaults(
    opts?: { forceSequential?: boolean }
  ): Promise<Map<string, Address>> {
    await this.initializationPromise;
    if (!this.account) {
      throw new NotConnectedError();
    }

    const vaultMap = new Map<string, Address>();
    const batchSize = 50;
    let offset = 0;

    while (true) {
      const vaultIdCalls = Array.from({ length: batchSize }, (_, i) => ({
        address: this.factoryAddress!,
        abi: quipFactoryAbi,
        functionName: "vaultIds" as const,
        args: [this.account!, BigInt(offset + i)] as const,
      }));

      const vaultIdResults = await tryMulticall(
        this.publicClient,
        vaultIdCalls,
        {
          chainId: this.chainId,
          ...(opts?.forceSequential && { forceSequential: true }),
        }
      );

      const validVaultIds: Hex[] = [];
      for (const r of vaultIdResults) {
        if (r.status === "success") {
          validVaultIds.push(r.result as Hex);
        } else {
          break; // past end of array
        }
      }

      if (validVaultIds.length === 0) break;

      const quipsCalls = validVaultIds.map((vaultId) => ({
        address: this.factoryAddress!,
        abi: quipFactoryAbi,
        functionName: "quips" as const,
        args: [this.account!, vaultId] as const,
      }));

      const quipsResults = await tryMulticall(
        this.publicClient,
        quipsCalls,
        {
          chainId: this.chainId,
          ...(opts?.forceSequential && { forceSequential: true }),
        }
      );

      for (let i = 0; i < validVaultIds.length; i++) {
        const r = quipsResults[i];
        if (
          r.status === "success" &&
          (r.result as Address) !== zeroAddress
        ) {
          vaultMap.set(validVaultIds[i], r.result as Address);
        }
      }

      if (validVaultIds.length < batchSize) break;
      offset += batchSize;
    }

    return vaultMap;
  }

  /// Snapshot of factory-level fees, ownership, and vetted impl pointer in
  /// a single multicall round-trip.
  async getFactoryState(
    opts?: { forceSequential?: boolean }
  ): Promise<FactoryState> {
    await this.initializationPromise;
    const calls = [
      { address: this.factoryAddress!, abi: quipFactoryAbi, functionName: "owner" as const },
      { address: this.factoryAddress!, abi: quipFactoryAbi, functionName: "pendingOwner" as const },
      { address: this.factoryAddress!, abi: quipFactoryAbi, functionName: "creationFee" as const },
      { address: this.factoryAddress!, abi: quipFactoryAbi, functionName: "executeFee" as const },
      { address: this.factoryAddress!, abi: quipFactoryAbi, functionName: "MAX_FEE" as const },
      { address: this.factoryAddress!, abi: quipFactoryAbi, functionName: "latestWalletImpl" as const },
      { address: this.factoryAddress!, abi: quipFactoryAbi, functionName: "getVettedCodeCount" as const },
    ];

    const results = await tryMulticall(this.publicClient, calls, {
      chainId: this.chainId,
      ...(opts?.forceSequential && { forceSequential: true }),
    });

    const labels = [
      "owner",
      "pendingOwner",
      "creationFee",
      "executeFee",
      "MAX_FEE",
      "latestWalletImpl",
      "getVettedCodeCount",
    ] as const;

    const failures: { label: string; error: Error }[] = [];
    for (let i = 0; i < results.length; i++) {
      const r = results[i];
      if (r.status === "failure") {
        failures.push({ label: labels[i], error: r.error });
      }
    }
    if (failures.length > 0) {
      throw new PartialMulticallResultError(failures);
    }

    return {
      owner: (results[0] as { status: "success"; result: Address }).result,
      pendingOwner: (results[1] as { status: "success"; result: Address }).result,
      creationFee: (results[2] as { status: "success"; result: bigint }).result,
      executeFee: (results[3] as { status: "success"; result: bigint }).result,
      maxFee: (results[4] as { status: "success"; result: bigint }).result,
      latestWalletImpl: (results[5] as { status: "success"; result: Address }).result,
      vettedCodeCount: (results[6] as { status: "success"; result: bigint }).result,
    };
  }
}
