/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace WOTSPlus {
  export type WinternitzAddressStruct = {
    publicSeed: BytesLike;
    publicKeyHash: BytesLike;
  };

  export type WinternitzAddressStructOutput = [
    publicSeed: string,
    publicKeyHash: string
  ] & { publicSeed: string; publicKeyHash: string };
}

export interface QuipFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "creationFee"
      | "depositToWinternitz"
      | "executeFee"
      | "owner"
      | "quips"
      | "setCreationFee"
      | "setExecuteFee"
      | "setTransferFee"
      | "transferFee"
      | "transferOwnership"
      | "vaultIds"
      | "withdraw"
      | "wotsLibrary"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "QuipCreated"): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "creationFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositToWinternitz",
    values: [BytesLike, AddressLike, WOTSPlus.WinternitzAddressStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "executeFee",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "quips",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setCreationFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setExecuteFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTransferFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultIds",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "wotsLibrary",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "creationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositToWinternitz",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "executeFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "quips", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setCreationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExecuteFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTransferFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vaultIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "wotsLibrary",
    data: BytesLike
  ): Result;
}

export namespace QuipCreatedEvent {
  export type InputTuple = [
    amount: BigNumberish,
    when: BigNumberish,
    vaultId: BytesLike,
    creator: AddressLike,
    pqPubkey: WOTSPlus.WinternitzAddressStruct,
    quip: AddressLike
  ];
  export type OutputTuple = [
    amount: bigint,
    when: bigint,
    vaultId: string,
    creator: string,
    pqPubkey: WOTSPlus.WinternitzAddressStructOutput,
    quip: string
  ];
  export interface OutputObject {
    amount: bigint;
    when: bigint;
    vaultId: string;
    creator: string;
    pqPubkey: WOTSPlus.WinternitzAddressStructOutput;
    quip: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface QuipFactory extends BaseContract {
  connect(runner?: ContractRunner | null): QuipFactory;
  waitForDeployment(): Promise<this>;

  interface: QuipFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  creationFee: TypedContractMethod<[], [bigint], "view">;

  depositToWinternitz: TypedContractMethod<
    [
      vaultId: BytesLike,
      to: AddressLike,
      pqTo: WOTSPlus.WinternitzAddressStruct
    ],
    [string],
    "payable"
  >;

  executeFee: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  quips: TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [string],
    "view"
  >;

  setCreationFee: TypedContractMethod<
    [newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setExecuteFee: TypedContractMethod<
    [newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTransferFee: TypedContractMethod<
    [newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferFee: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  vaultIds: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  withdraw: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  wotsLibrary: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "creationFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositToWinternitz"
  ): TypedContractMethod<
    [
      vaultId: BytesLike,
      to: AddressLike,
      pqTo: WOTSPlus.WinternitzAddressStruct
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "executeFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "quips"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "setCreationFee"
  ): TypedContractMethod<[newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setExecuteFee"
  ): TypedContractMethod<[newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTransferFee"
  ): TypedContractMethod<[newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vaultIds"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "wotsLibrary"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "QuipCreated"
  ): TypedContractEvent<
    QuipCreatedEvent.InputTuple,
    QuipCreatedEvent.OutputTuple,
    QuipCreatedEvent.OutputObject
  >;

  filters: {
    "QuipCreated(uint256,uint256,bytes32,address,tuple,address)": TypedContractEvent<
      QuipCreatedEvent.InputTuple,
      QuipCreatedEvent.OutputTuple,
      QuipCreatedEvent.OutputObject
    >;
    QuipCreated: TypedContractEvent<
      QuipCreatedEvent.InputTuple,
      QuipCreatedEvent.OutputTuple,
      QuipCreatedEvent.OutputObject
    >;
  };
}
